# Generated by Django 2.2.12 on 2020-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=255),
        ),
    ]
